# Generated by Django 4.1.7 on 2023-02-25 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('product', models.ForeignKey(db_column='product', on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
            options={
                'db_table': 'Carts',
            },
        ),
    ]
